feat: integrate new canonicalize schemas
near/fast-auth-signer pull request #201
Opened 2024-03-25 21:13 UTC by esaminu

Add new schemas and logic integrating canonicalized json as outlined in https://github.com/near/near-fastauth-wallet/pull/15

2024-03-25 22:26 UTC, hcho112 commented on packages/near-fast-auth-signer/src/components/SignMultichain/SignMultichain.tsx
> +          window.parent.postMessage({ type: 'response', message: `Successfully sign and send transaction, ${response.transactionHash}` }, '*');
Would this change also reflect on `near-fastauth-wallet`?

2024-03-25 22:45 UTC, hcho112 commented on packages/near-fast-auth-signer/src/components/SignMultichain/SignMultichain.tsx
> +          if (transaction?.domain === window.parent.origin) {
is this part of code work? I saw an error message when I attempt to access `window.parent.origin`.

2024-03-25 22:59 UTC, hcho112 commented on packages/near-fast-auth-signer/src/components/SignMultichain/utils.ts
> +  if (chain === 0) {
lets leave a comment saying // is BTC

2024-03-25 23:04 UTC, hcho112 reviewed
left few minor comment. Would there be a matching change happening on near-fastauth-wallet and demo dApp?

2024-03-26 00:04 UTC, esaminu commented
Resolved the comments thanks for spotting. Yes there will be some changes to the posted payload from `near-fastauth-wallet`

2024-03-26 01:59 UTC, hcho112 submitted a review, later dismissed
LGTM, great work

2024-03-26 20:03 UTC, Pessina requested changes

2024-03-26 20:03 UTC, Pessina commented on packages/near-fast-auth-signer/src/components/SignMultichain/utils.ts
> +    chainId: (signMultichainRequest as EvmSendMultichainMessage).chainId,
Instead of casting, can we do it with type guards?

I know it will be more code, but add some extra safety and readability to the code.

2024-03-26 20:03 UTC, Pessina commented on packages/near-fast-auth-signer/src/components/SignMultichain/utils.ts
> +  if (chainDetails.chain === 60) {
Same as the previous comment, properly type it to get errors in case we add/remove chain and forget to update here

2024-03-26 20:03 UTC, Pessina commented on packages/near-fast-auth-signer/src/components/SignMultichain/utils.ts
> +  if (chain === 0) {
Same as the previous comment, properly type it to get errors in case we add/remove chain and forget to update here

2024-03-26 23:21 UTC, Pessina requested changes

2024-03-26 23:21 UTC, Pessina commented on packages/near-fast-auth-signer/src/components/SignMultichain/utils.ts
> +  chain: SLIP044ChainId;
You are only typing it, but not enforcing to the defined a scenario for each chain. 

You can see it on this screenshot. 

<img width="758" alt="Screenshot 2024-03-27 at 3 19 48 AM" src="https://github.com/near/fast-auth-signer/assets/22358004/48f95c20-9c2e-4e5e-b365-51a66043c373">
<img width="750" alt="Screenshot 2024-03-27 at 3 19 21 AM" src="https://github.com/near/fast-auth-signer/assets/22358004/501feb62-6249-4f94-a33b-1aff3e236a80">
<img width="763" alt="Screenshot 2024-03-27 at 3 19 35 AM" src="https://github.com/near/fast-auth-signer/assets/22358004/2dad35ec-f149-4492-95ad-57e24cfa3a2c">

In order to enforce defining one if per chain you have to use a assertNever at the end.

2024-03-27 00:30 UTC, Pessina approved these changes

2024-03-27 00:36 UTC, merged